### ISSUE TITLE
⚡ Feature | New Editor

### ISSUE THREAD

**Issue by pradel** [sigle/sigle#252]
## Description

We are migrating from Slate to TipTap for the editor.
The editor will be merged bit by bit to make the review easier, then we will replace slate when everything is ready.
This issue will be used to track related issues / improvements.

You can find a demo at any time here https://app.sigle.io/tiptap-editor.

## Improvements

- [x] Markdown support (https://github.com/pradel/sigle/issues/87)
- [x] add support for strikeThrough (https://github.com/pradel/sigle/issues/293)
- [x] Improved link flow
- [x] Slash commands (like notion)
- [x] GIF support
- [x] Code blocks
- [x] Divider blocks
- [x] Show world count on the editor page (https://github.com/pradel/sigle/issues/188)
- [ ] Image with caption (https://github.com/pradel/sigle/issues/53)
- [ ] Auto-save (https://github.com/pradel/sigle/issues/273)
- [ ] Select size of the image (https://github.com/pradel/sigle/issues/248)
- [ ] Mobile support

## Bugs

- [x] cmd+z does not undo previous action (https://github.com/pradel/sigle/issues/242)
- [x]  Issues with add a link shortcut (ctrl+k) (https://github.com/pradel/sigle/issues/116)
