### ISSUE TITLE
⚡ Feature | Collect user emails

### ISSUE THREAD

**Issue by pradel** [sigle/sigle#705]
## Description

After a user creates an account, we should ask him to optionally enter his email to receive transactional emails and updates about the product.
The settings should also allow a user to change his email and preferences.

### Tasks

- [ ] UI to enter the email
- [ ] Design email template with MJML
- [ ] Validate email via link
- [ ] Settings to change the email
- [ ] Settings to change the preferences and unsubscribe

### Issues

- [x] https://github.com/sigle/sigle/issues/727
- [x] https://github.com/sigle/sigle/issues/728
- [x] https://github.com/sigle/sigle/issues/729
