### ISSUE TITLE
⚡ Sigle next tracking issue

### ISSUE THREAD

**Issue by pradel** [sigle/sigle#817]
## Description

- [x] Ceramic Staging node deployed
- [x] Use latest tailwind global config option
- [x] Setup PostHog
- [x] Editor Link cross icon
- [x] Beta banner
- [ ] Publish should save auto
- [x] New tailwind typography config
- [ ] `TipTap` convert HTML to markdown to save on Ceramic
- [ ] `TipTapTwitter` extension
- [ ] `TipTapCta` extension
- [ ] `TipTap Markdown` Image caption with link etc https://github.com/Antonio-Laguna/markdown-it-image-figures
- [ ] `TipTap Oembed` - https://www.npmjs.com/package/markdown-it-oembed ?
- [ ] Link `sigle/src/modules/editor/EditorShortcuts/ShortcutsDialog.tsx` in the editor
- [ ] Editor story settings validation. Eg: canonical URL should be a link
- [ ] Plausible and fathom
- [ ] Collapse menu save in local storage
- [ ] Encrypt drafts
- [ ] Cron job to delete uploaded images that have been deleted
- [ ] Verify that Sentry Next.js sourcemaps are working
